name: Continuous integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.4
        env:
          MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
          MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
          #          MARIADB_USER: ${{ secrets.MARIADB_USER }}
          #          MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --host=127.0.0.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Set up the .env.test file
        run: |
          echo "DATABASE_URL=mysql://root:${{ secrets.MARIADB_ROOT_PASSWORD }}@127.0.0.1:3306/${{ secrets.MARIADB_DATABASE }}?serverVersion=8.2&charset=utf8mb4" > .env.test

      - name: Create the test database
        run: php bin/console doctrine:database:create --env=test

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Run tests
        run: |
          vendor/bin/phpunit
        env:
          DATABASE_ENDPOINT: 127.0.0.1:3306

      - name: Upload test results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/logs

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
